rgv不带参会报错。
```
Traceback (most recent call last):
  File "/usr/bin/rgv", line 355, in <module>
    view()
  File "/usr/bin/rgv", line 350, in view
    cat(logfile)
  File "/usr/bin/rgv", line 296, in cat
    display = Display(basedir)
TypeError: __init__() missing 1 required positional argument: 'isatty'
```